### ISSUE TITLE
Thank you very much for developing this software, and I want to give you some feedback.

### ISSUE THREAD

**Issue by Kagarino11** [Valkirie/AyaGyroAiming#1]
When I started using the 0.10 version, I was very surprised. The software has successfully run on aya neo, but the sensitivity is very low, consistent with the sensitivity of the right stick. So I look forward to the next version very much. When I started using version 0.13, the sensitivity and direction were very strange. In version 0.16, the software is no longer available after the prerequisites are installed. Then, how your this software can be used on cemu, and hide hide will not work on steam.
Finally, a Chinese player once again expresses his gratitude to you

**Comment by Valkirie** [comment]
As of 0.16 you have to either:
- change the default **EnableGyroAiming** settings value to enable gyro aiming on all applications (_use the command **/set EnableGyroAiming true** inside the console_)
- create an ini file inside the **inis** folder where you'll set application specific settings (_you have to name your ini file using the target executable name, like: destiny2.ini, witcher3.ini. Use example.ini as a basis._)

**Comment by Kagarino11** [comment]
Thanks for your reply, but it still doesn’t work. I changed Enblegyroaiming to true and it doesn’t work. I also tried to add the default file. The new csgo.ini failed to run in csgo. Changing X, Y, and Z to true still failed. Steam The gyroscope cannot be recognized by the calibration. Versions 0.10 and 0.13 are available.

**Comment by Valkirie** [comment]
What happens when you use /cpl to display the controller settings window, can you see your gyro movement affecting the right stick ? Please note that, as of today, many games will just ignore the virtual controller because we can't properly hide the physical one due to a bug with HidHide (https://github.com/ViGEm/HidHide).
> a fixed HidHide build is coming soon

**Comment by heathenlethal** [comment]
wow, was really happy to find this because aya totally failed us when it comes to these gyro controls they raved about. i cant seem to get this to work though, am i missing instructions or a tutorial somewhere?

thanks so much for releasing this though

**Comment by Kagarino11** [comment]
It can already run normally on cemu. Steam and games can recognize the virtual controller, but cannot control the right joystick through the gyroscope. It can be controlled by 0.10 and 0.13. Hide hide is useless. I tried it many times, but it didn’t. Hide the physical controller.

**Comment by Valkirie** [comment]
> It can already run normally on cemu. Steam and games can recognize the virtual controller, but cannot control the right joystick through the gyroscope. It can be controlled by 0.10 and 0.13. Hide hide is useless. I tried it many times, but it didn’t. Hide the physical controller.

Please note that on **CEMU, Yuzu and Ryujinx**, you might actually want to turn the **GyroAiming** off and rely exlusively on **Gamepad motion source** using Cemuhook (https://cemuhook.sshnuke.net/). You'll get both the gyroscope and accelerometer working together to provide the exact WiiU experience (https://streamable.com/ah4rqy) without affecting the right stick.

![image](https://user-images.githubusercontent.com/934757/126596839-5fe6a3fd-cbf6-45ce-8935-8320d7cbd2ca.png)

Regarding HidHide we have to wait. There is nothing I can do about it right now.

**Comment by Valkirie** [comment]
> wow, was really happy to find this because aya totally failed us when it comes to these gyro controls they raved about. i cant seem to get this to work though, am i missing instructions or a tutorial somewhere?
> 
> thanks so much for releasing this though

Yes I should definitely work on a tutorial. First time you start the application you can either type the below command:
> /set EnableGyroAiming true

Or, create an ini profile for each application inside the /inis/ folder where your configuration file is the executable filename.
See the following commit: https://github.com/Valkirie/AyaGyroAiming/commit/cc36a1f88a764afae79f70a2d081ad256ddbc507

**Comment by heathenlethal** [comment]
but it doesnt work with steam then? would there be any way to spoof the aya as a ds4 controller in steam?

**Comment by Kagarino11** [comment]
Thank you, I have been running perfectly for several days. With your help, the problem has been solved. I have sent the software to a few friends and it has started to spread in the aya circle. We are all very happy. Software, we have a better experience, thank you again for your production and sharing

**Comment by heathenlethal** [comment]
> Thank you, I have been running perfectly for several days. With your help, the problem has been solved. I have sent the software to a few friends and it has started to spread in the aya circle. We are all very happy. Software, we have a better experience, thank you again for your production and sharing

works on steam too?

**Comment by Kagarino11** [comment]
> > Thank you, I have been running perfectly for several days. With your help, the problem has been solved. I have sent the software to a few friends and it has started to spread in the aya circle. We are all very happy. Software, we have a better experience, thank you again for your production and sharing
> 
> works on steam too?

Yep

**Comment by heathenlethal** [comment]
> > > Thank you, I have been running perfectly for several days. With your help, the problem has been solved. I have sent the software to a few friends and it has started to spread in the aya circle. We are all very happy. Software, we have a better experience, thank you again for your production and sharing
> > 
> > 
> > works on steam too?
> 
> Yep

Do we have to boot up hidhide as well?
Is it possible to quickly go over the steps you did to get it working? Would be greatly appreciated :)

**Comment by lucas00z** [comment]
I use version 17 to play apex. The gyroscope is upside down. The author keeps on cheering.I love u
LOL

**Comment by heathenlethal** [comment]
wow i got it to work.pretty awesome! using it on doom 3. is there any way to activate it with the press of a certain key? like L2 activates it or something?

**Comment by heathenlethal** [comment]
also i noticed theres some lag, can threshhold, magnitude or range change this?

**Comment by Valkirie** [comment]
> wow i got it to work.pretty awesome! using it on doom 3. is there any way to activate it with the press of a certain key? like L2 activates it or something?

I'll work on it soon for a next release :)

**Comment by Valkirie** [comment]
> I use version 17 to play apex. The gyroscope is upside down. The author keeps on cheering.I love u
> LOL

Create a specific ini file inside the inis folder (executable.ini) and change any of the below:
> GyroStickInvertAxisX=false
> GyroStickInvertAxisY=false
> GyroStickInvertAxisZ=false

**Comment by Valkirie** [comment]
> > > > Thank you, I have been running perfectly for several days. With your help, the problem has been solved. I have sent the software to a few friends and it has started to spread in the aya circle. We are all very happy. Software, we have a better experience, thank you again for your production and sharing
> > > 
> > > 
> > > works on steam too?
> > 
> > 
> > Yep
> 
> Do we have to boot up hidhide as well?
> Is it possible to quickly go over the steps you did to get it working? Would be greatly appreciated :)

HidHide doesnt work properly as of today. Over steam you can force an application to use exclusively a gamepad.

**Comment by Valkirie** [comment]
Please reopen if still not satisfied with release 0.18.
