### ISSUE TITLE
reduce latency?

### ISSUE THREAD

**Issue by heathenlethal** [Valkirie/AyaGyroAiming#2]
I noticed theres some lag before the gyro registers movement. is there any way to fix or reduce this?

**Comment by Valkirie** [comment]
Hi, sorry for the late reply, I'm on holiday with limited access to computer.
You should try and reduce the **GyroMaxSample** to 4 (instead of 10).
> /set GyroMaxSample 4

**Comment by heathenlethal** [comment]
thanks for the reply. i hope youre having a great holiday! that seemed to help a bit. but it seems what im looking for is responsiveness. sometimes its hard to get the cursor in the spot you want it. ive used the switch gyro and steam controller gyro, so i know im doing something wrong here. its still good. but the accuracy or responsiveness of the gyro i guess is a bit off. ive been messing with threshhold, magnitude and range, which of these do you think will help? not sure what they do.

**Comment by Valkirie** [comment]
Hang in there, making progresses lately : https://streamable.com/xxuph3

**Comment by Valkirie** [comment]
Please reopen if still not satisfied with release 0.18.
