### ISSUE TITLE
Gyro doesn't feel quite right

### ISSUE THREAD

**Issue by ghost** [Valkirie/AyaGyroAiming#3]
Been using v0.17 with some indie PC games and I don't know if it's because of the game or not but something about the gyro doesn't feel quite right, I have tried changing the settings but it doesn't seem to fix the issue, I'll do my best to explain why it doesn't feel quite right.

Gyro is working perfectly when moving the Neo around however it seems to get "stuck", I don't know if it's a latency issue as another user reported as it's responsive but when playing a FPS the reticle seems to get stuck when trying to move on the X axis, the Y axis is responsive but seems to "jump" position for example when I move the Neo to look up a little it sends the reticle up/down much more than intended, I don't know if I'm explaining properly but this isn't how I remember gyro worked on a device like the Switch where slight movements is enough to correct the reticle while not jumping all over the place but that might be because it's game specific so I'll try on either Yuzu or Ryujinx with Fatal Bullet as that's my experience with gyro and report back later.

I have tried the newest build of HidHide and it seems to work properly, kinda, it shows two Xbox 360 controllers instead of one for some reason but I'm glad it works. 

I'll add more once I tried other games but wanted to get my feedback down before I forget and in case this can be fixed after your holiday.

**Comment by jacksonmancage** [comment]
yeah stuck is a good description. it would be amazing if he could make it sensitive like the switch’s

**Comment by Valkirie** [comment]
Deadzone might be involved here. Let me investigate :)

**Comment by Valkirie** [comment]
Making progresses lately : https://streamable.com/xxuph3

**Comment by Valkirie** [comment]
Please reopen if still not satisfied with release 0.18.
